version: '3.4'

services:
  server:
    container_name: ng-shop-server
    build: docker/server
    ports:
      - 8090:8090
      - 5858:5858
    volumes:
      - ./:/var/www/ng-shop
    environment:
      - COMPOSE_HTTP_TIMEOUT=300
    tty: true
    command: /docker-entrypoint.sh
    depends_on:
      - mongodb
    networks:
      - ng-shop-network

  mongodb:
    image: mongo:latest
    container_name: ng-shop-mongodb
    ports:
      - 27017:27017
    networks:
      - ng-shop-network

networks:
  ng-shop-network:
    external: true
